# Generated by Django 6.0.6 on 2026-06-09 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(db_index=True, max_length=10)),
                ('loc', models.CharField(choices=[('W311A', 'W311A'), ('W311D-Z1', 'W311D-Z1'), ('W311D-Z2', 'W311D-Z2'), ('W311-H1', 'W311-H1'), ('W311-H2', 'W311-H2'), ('W311-H3', 'W311-H3')], db_index=True, max_length=10)),
                ('temp', models.FloatField()),
                ('hum', models.FloatField()),
                ('light', models.FloatField()),
                ('snd', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['loc', '-timestamp'], name='smart_campu_loc_2d26e8_idx'), models.Index(fields=['node_id', '-timestamp'], name='smart_campu_node_id_8c6d99_idx')],
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='warning', max_length=10)),
                ('alert_type', models.CharField(max_length=50)),
                ('room', models.CharField(db_index=True, max_length=10)),
                ('message', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='active', max_length=15)),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_campus.sensorreading')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue', models.CharField(choices=[('W311A', 'W311A Computer Room'), ('W311D-Z1', 'W311D Z1'), ('W311D-Z2', 'W311D Z2'), ('W311-H1', 'W311 H1'), ('W311-H2', 'W311 H2'), ('W311-H3', 'W311 H3')], db_index=True, max_length=10)),
                ('event_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_title', models.CharField(max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['event_date', 'start_time'],
                'indexes': [models.Index(fields=['venue', 'event_date'], name='smart_campu_venue_362308_idx')],
            },
        ),
    ]
